ALTER TABLE groups ADD COLUMN IF NOT EXISTS simulate_cache_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS simulate_cache_ratio DECIMAL(5,4) NOT NULL DEFAULT 0.7000;
