// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelpricing"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelPricingUpdate is the builder for updating ModelPricing entities.
type ModelPricingUpdate struct {
	config
	hooks    []Hook
	mutation *ModelPricingMutation
}

// Where appends a list predicates to the ModelPricingUpdate builder.
func (_u *ModelPricingUpdate) Where(ps ...predicate.ModelPricing) *ModelPricingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *ModelPricingUpdate) SetModelName(v string) *ModelPricingUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableModelName(v *string) *ModelPricingUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetInputCostPerToken sets the "input_cost_per_token" field.
func (_u *ModelPricingUpdate) SetInputCostPerToken(v float64) *ModelPricingUpdate {
	_u.mutation.ResetInputCostPerToken()
	_u.mutation.SetInputCostPerToken(v)
	return _u
}

// SetNillableInputCostPerToken sets the "input_cost_per_token" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableInputCostPerToken(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetInputCostPerToken(*v)
	}
	return _u
}

// AddInputCostPerToken adds value to the "input_cost_per_token" field.
func (_u *ModelPricingUpdate) AddInputCostPerToken(v float64) *ModelPricingUpdate {
	_u.mutation.AddInputCostPerToken(v)
	return _u
}

// ClearInputCostPerToken clears the value of the "input_cost_per_token" field.
func (_u *ModelPricingUpdate) ClearInputCostPerToken() *ModelPricingUpdate {
	_u.mutation.ClearInputCostPerToken()
	return _u
}

// SetOutputCostPerToken sets the "output_cost_per_token" field.
func (_u *ModelPricingUpdate) SetOutputCostPerToken(v float64) *ModelPricingUpdate {
	_u.mutation.ResetOutputCostPerToken()
	_u.mutation.SetOutputCostPerToken(v)
	return _u
}

// SetNillableOutputCostPerToken sets the "output_cost_per_token" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableOutputCostPerToken(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetOutputCostPerToken(*v)
	}
	return _u
}

// AddOutputCostPerToken adds value to the "output_cost_per_token" field.
func (_u *ModelPricingUpdate) AddOutputCostPerToken(v float64) *ModelPricingUpdate {
	_u.mutation.AddOutputCostPerToken(v)
	return _u
}

// ClearOutputCostPerToken clears the value of the "output_cost_per_token" field.
func (_u *ModelPricingUpdate) ClearOutputCostPerToken() *ModelPricingUpdate {
	_u.mutation.ClearOutputCostPerToken()
	return _u
}

// SetCacheReadInputTokenCost sets the "cache_read_input_token_cost" field.
func (_u *ModelPricingUpdate) SetCacheReadInputTokenCost(v float64) *ModelPricingUpdate {
	_u.mutation.ResetCacheReadInputTokenCost()
	_u.mutation.SetCacheReadInputTokenCost(v)
	return _u
}

// SetNillableCacheReadInputTokenCost sets the "cache_read_input_token_cost" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableCacheReadInputTokenCost(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetCacheReadInputTokenCost(*v)
	}
	return _u
}

// AddCacheReadInputTokenCost adds value to the "cache_read_input_token_cost" field.
func (_u *ModelPricingUpdate) AddCacheReadInputTokenCost(v float64) *ModelPricingUpdate {
	_u.mutation.AddCacheReadInputTokenCost(v)
	return _u
}

// ClearCacheReadInputTokenCost clears the value of the "cache_read_input_token_cost" field.
func (_u *ModelPricingUpdate) ClearCacheReadInputTokenCost() *ModelPricingUpdate {
	_u.mutation.ClearCacheReadInputTokenCost()
	return _u
}

// SetCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field.
func (_u *ModelPricingUpdate) SetCacheCreationInputTokenCost(v float64) *ModelPricingUpdate {
	_u.mutation.ResetCacheCreationInputTokenCost()
	_u.mutation.SetCacheCreationInputTokenCost(v)
	return _u
}

// SetNillableCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableCacheCreationInputTokenCost(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetCacheCreationInputTokenCost(*v)
	}
	return _u
}

// AddCacheCreationInputTokenCost adds value to the "cache_creation_input_token_cost" field.
func (_u *ModelPricingUpdate) AddCacheCreationInputTokenCost(v float64) *ModelPricingUpdate {
	_u.mutation.AddCacheCreationInputTokenCost(v)
	return _u
}

// ClearCacheCreationInputTokenCost clears the value of the "cache_creation_input_token_cost" field.
func (_u *ModelPricingUpdate) ClearCacheCreationInputTokenCost() *ModelPricingUpdate {
	_u.mutation.ClearCacheCreationInputTokenCost()
	return _u
}

// SetIsCustom sets the "is_custom" field.
func (_u *ModelPricingUpdate) SetIsCustom(v bool) *ModelPricingUpdate {
	_u.mutation.SetIsCustom(v)
	return _u
}

// SetNillableIsCustom sets the "is_custom" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableIsCustom(v *bool) *ModelPricingUpdate {
	if v != nil {
		_u.SetIsCustom(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *ModelPricingUpdate) SetNote(v string) *ModelPricingUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableNote(v *string) *ModelPricingUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelPricingUpdate) SetUpdatedAt(v time.Time) *ModelPricingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFastPriceMultiplier sets the "fast_price_multiplier" field.
func (_u *ModelPricingUpdate) SetFastPriceMultiplier(v float64) *ModelPricingUpdate {
	_u.mutation.ResetFastPriceMultiplier()
	_u.mutation.SetFastPriceMultiplier(v)
	return _u
}

// SetNillableFastPriceMultiplier sets the "fast_price_multiplier" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableFastPriceMultiplier(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetFastPriceMultiplier(*v)
	}
	return _u
}

// AddFastPriceMultiplier adds value to the "fast_price_multiplier" field.
func (_u *ModelPricingUpdate) AddFastPriceMultiplier(v float64) *ModelPricingUpdate {
	_u.mutation.AddFastPriceMultiplier(v)
	return _u
}

// ClearFastPriceMultiplier clears the value of the "fast_price_multiplier" field.
func (_u *ModelPricingUpdate) ClearFastPriceMultiplier() *ModelPricingUpdate {
	_u.mutation.ClearFastPriceMultiplier()
	return _u
}

// Mutation returns the ModelPricingMutation object of the builder.
func (_u *ModelPricingUpdate) Mutation() *ModelPricingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelPricingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPricingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelPricingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPricingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelPricingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelpricing.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelPricingUpdate) check() error {
	if v, ok := _u.mutation.ModelName(); ok {
		if err := modelpricing.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.model_name": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelPricingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelpricing.Table, modelpricing.Columns, sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(modelpricing.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputCostPerToken(); ok {
		_spec.SetField(modelpricing.FieldInputCostPerToken, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputCostPerToken(); ok {
		_spec.AddField(modelpricing.FieldInputCostPerToken, field.TypeFloat64, value)
	}
	if _u.mutation.InputCostPerTokenCleared() {
		_spec.ClearField(modelpricing.FieldInputCostPerToken, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputCostPerToken(); ok {
		_spec.SetField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputCostPerToken(); ok {
		_spec.AddField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64, value)
	}
	if _u.mutation.OutputCostPerTokenCleared() {
		_spec.ClearField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadInputTokenCost(); ok {
		_spec.SetField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadInputTokenCost(); ok {
		_spec.AddField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadInputTokenCostCleared() {
		_spec.ClearField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheCreationInputTokenCost(); ok {
		_spec.SetField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationInputTokenCost(); ok {
		_spec.AddField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64, value)
	}
	if _u.mutation.CacheCreationInputTokenCostCleared() {
		_spec.ClearField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IsCustom(); ok {
		_spec.SetField(modelpricing.FieldIsCustom, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(modelpricing.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpricing.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FastPriceMultiplier(); ok {
		_spec.SetField(modelpricing.FieldFastPriceMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFastPriceMultiplier(); ok {
		_spec.AddField(modelpricing.FieldFastPriceMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.FastPriceMultiplierCleared() {
		_spec.ClearField(modelpricing.FieldFastPriceMultiplier, field.TypeFloat64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpricing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelPricingUpdateOne is the builder for updating a single ModelPricing entity.
type ModelPricingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelPricingMutation
}

// SetModelName sets the "model_name" field.
func (_u *ModelPricingUpdateOne) SetModelName(v string) *ModelPricingUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableModelName(v *string) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetInputCostPerToken sets the "input_cost_per_token" field.
func (_u *ModelPricingUpdateOne) SetInputCostPerToken(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetInputCostPerToken()
	_u.mutation.SetInputCostPerToken(v)
	return _u
}

// SetNillableInputCostPerToken sets the "input_cost_per_token" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableInputCostPerToken(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetInputCostPerToken(*v)
	}
	return _u
}

// AddInputCostPerToken adds value to the "input_cost_per_token" field.
func (_u *ModelPricingUpdateOne) AddInputCostPerToken(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddInputCostPerToken(v)
	return _u
}

// ClearInputCostPerToken clears the value of the "input_cost_per_token" field.
func (_u *ModelPricingUpdateOne) ClearInputCostPerToken() *ModelPricingUpdateOne {
	_u.mutation.ClearInputCostPerToken()
	return _u
}

// SetOutputCostPerToken sets the "output_cost_per_token" field.
func (_u *ModelPricingUpdateOne) SetOutputCostPerToken(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetOutputCostPerToken()
	_u.mutation.SetOutputCostPerToken(v)
	return _u
}

// SetNillableOutputCostPerToken sets the "output_cost_per_token" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableOutputCostPerToken(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetOutputCostPerToken(*v)
	}
	return _u
}

// AddOutputCostPerToken adds value to the "output_cost_per_token" field.
func (_u *ModelPricingUpdateOne) AddOutputCostPerToken(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddOutputCostPerToken(v)
	return _u
}

// ClearOutputCostPerToken clears the value of the "output_cost_per_token" field.
func (_u *ModelPricingUpdateOne) ClearOutputCostPerToken() *ModelPricingUpdateOne {
	_u.mutation.ClearOutputCostPerToken()
	return _u
}

// SetCacheReadInputTokenCost sets the "cache_read_input_token_cost" field.
func (_u *ModelPricingUpdateOne) SetCacheReadInputTokenCost(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetCacheReadInputTokenCost()
	_u.mutation.SetCacheReadInputTokenCost(v)
	return _u
}

// SetNillableCacheReadInputTokenCost sets the "cache_read_input_token_cost" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableCacheReadInputTokenCost(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetCacheReadInputTokenCost(*v)
	}
	return _u
}

// AddCacheReadInputTokenCost adds value to the "cache_read_input_token_cost" field.
func (_u *ModelPricingUpdateOne) AddCacheReadInputTokenCost(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddCacheReadInputTokenCost(v)
	return _u
}

// ClearCacheReadInputTokenCost clears the value of the "cache_read_input_token_cost" field.
func (_u *ModelPricingUpdateOne) ClearCacheReadInputTokenCost() *ModelPricingUpdateOne {
	_u.mutation.ClearCacheReadInputTokenCost()
	return _u
}

// SetCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field.
func (_u *ModelPricingUpdateOne) SetCacheCreationInputTokenCost(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetCacheCreationInputTokenCost()
	_u.mutation.SetCacheCreationInputTokenCost(v)
	return _u
}

// SetNillableCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableCacheCreationInputTokenCost(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetCacheCreationInputTokenCost(*v)
	}
	return _u
}

// AddCacheCreationInputTokenCost adds value to the "cache_creation_input_token_cost" field.
func (_u *ModelPricingUpdateOne) AddCacheCreationInputTokenCost(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddCacheCreationInputTokenCost(v)
	return _u
}

// ClearCacheCreationInputTokenCost clears the value of the "cache_creation_input_token_cost" field.
func (_u *ModelPricingUpdateOne) ClearCacheCreationInputTokenCost() *ModelPricingUpdateOne {
	_u.mutation.ClearCacheCreationInputTokenCost()
	return _u
}

// SetIsCustom sets the "is_custom" field.
func (_u *ModelPricingUpdateOne) SetIsCustom(v bool) *ModelPricingUpdateOne {
	_u.mutation.SetIsCustom(v)
	return _u
}

// SetNillableIsCustom sets the "is_custom" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableIsCustom(v *bool) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetIsCustom(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *ModelPricingUpdateOne) SetNote(v string) *ModelPricingUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableNote(v *string) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelPricingUpdateOne) SetUpdatedAt(v time.Time) *ModelPricingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFastPriceMultiplier sets the "fast_price_multiplier" field.
func (_u *ModelPricingUpdateOne) SetFastPriceMultiplier(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetFastPriceMultiplier()
	_u.mutation.SetFastPriceMultiplier(v)
	return _u
}

// SetNillableFastPriceMultiplier sets the "fast_price_multiplier" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableFastPriceMultiplier(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetFastPriceMultiplier(*v)
	}
	return _u
}

// AddFastPriceMultiplier adds value to the "fast_price_multiplier" field.
func (_u *ModelPricingUpdateOne) AddFastPriceMultiplier(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddFastPriceMultiplier(v)
	return _u
}

// ClearFastPriceMultiplier clears the value of the "fast_price_multiplier" field.
func (_u *ModelPricingUpdateOne) ClearFastPriceMultiplier() *ModelPricingUpdateOne {
	_u.mutation.ClearFastPriceMultiplier()
	return _u
}

// Mutation returns the ModelPricingMutation object of the builder.
func (_u *ModelPricingUpdateOne) Mutation() *ModelPricingMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelPricingUpdate builder.
func (_u *ModelPricingUpdateOne) Where(ps ...predicate.ModelPricing) *ModelPricingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelPricingUpdateOne) Select(field string, fields ...string) *ModelPricingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelPricing entity.
func (_u *ModelPricingUpdateOne) Save(ctx context.Context) (*ModelPricing, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPricingUpdateOne) SaveX(ctx context.Context) *ModelPricing {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelPricingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPricingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelPricingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelpricing.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelPricingUpdateOne) check() error {
	if v, ok := _u.mutation.ModelName(); ok {
		if err := modelpricing.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.model_name": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelPricingUpdateOne) sqlSave(ctx context.Context) (_node *ModelPricing, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelpricing.Table, modelpricing.Columns, sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelPricing.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelpricing.FieldID)
		for _, f := range fields {
			if !modelpricing.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelpricing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(modelpricing.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputCostPerToken(); ok {
		_spec.SetField(modelpricing.FieldInputCostPerToken, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputCostPerToken(); ok {
		_spec.AddField(modelpricing.FieldInputCostPerToken, field.TypeFloat64, value)
	}
	if _u.mutation.InputCostPerTokenCleared() {
		_spec.ClearField(modelpricing.FieldInputCostPerToken, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputCostPerToken(); ok {
		_spec.SetField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputCostPerToken(); ok {
		_spec.AddField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64, value)
	}
	if _u.mutation.OutputCostPerTokenCleared() {
		_spec.ClearField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadInputTokenCost(); ok {
		_spec.SetField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadInputTokenCost(); ok {
		_spec.AddField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadInputTokenCostCleared() {
		_spec.ClearField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheCreationInputTokenCost(); ok {
		_spec.SetField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationInputTokenCost(); ok {
		_spec.AddField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64, value)
	}
	if _u.mutation.CacheCreationInputTokenCostCleared() {
		_spec.ClearField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IsCustom(); ok {
		_spec.SetField(modelpricing.FieldIsCustom, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(modelpricing.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpricing.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FastPriceMultiplier(); ok {
		_spec.SetField(modelpricing.FieldFastPriceMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFastPriceMultiplier(); ok {
		_spec.AddField(modelpricing.FieldFastPriceMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.FastPriceMultiplierCleared() {
		_spec.ClearField(modelpricing.FieldFastPriceMultiplier, field.TypeFloat64)
	}
	_node = &ModelPricing{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpricing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
