// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/modelpricing"
)

// ModelPricing is the model entity for the ModelPricing schema.
type ModelPricing struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ModelName holds the value of the "model_name" field.
	ModelName string `json:"model_name,omitempty"`
	// InputCostPerToken holds the value of the "input_cost_per_token" field.
	InputCostPerToken *float64 `json:"input_cost_per_token,omitempty"`
	// OutputCostPerToken holds the value of the "output_cost_per_token" field.
	OutputCostPerToken *float64 `json:"output_cost_per_token,omitempty"`
	// CacheReadInputTokenCost holds the value of the "cache_read_input_token_cost" field.
	CacheReadInputTokenCost *float64 `json:"cache_read_input_token_cost,omitempty"`
	// CacheCreationInputTokenCost holds the value of the "cache_creation_input_token_cost" field.
	CacheCreationInputTokenCost *float64 `json:"cache_creation_input_token_cost,omitempty"`
	// IsCustom holds the value of the "is_custom" field.
	IsCustom bool `json:"is_custom,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelPricing) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelpricing.FieldIsCustom:
			values[i] = new(sql.NullBool)
		case modelpricing.FieldInputCostPerToken, modelpricing.FieldOutputCostPerToken, modelpricing.FieldCacheReadInputTokenCost, modelpricing.FieldCacheCreationInputTokenCost:
			values[i] = new(sql.NullFloat64)
		case modelpricing.FieldID:
			values[i] = new(sql.NullInt64)
		case modelpricing.FieldModelName, modelpricing.FieldNote:
			values[i] = new(sql.NullString)
		case modelpricing.FieldCreatedAt, modelpricing.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelPricing fields.
func (_m *ModelPricing) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelpricing.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case modelpricing.FieldModelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_name", values[i])
			} else if value.Valid {
				_m.ModelName = value.String
			}
		case modelpricing.FieldInputCostPerToken:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_cost_per_token", values[i])
			} else if value.Valid {
				_m.InputCostPerToken = new(float64)
				*_m.InputCostPerToken = value.Float64
			}
		case modelpricing.FieldOutputCostPerToken:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_cost_per_token", values[i])
			} else if value.Valid {
				_m.OutputCostPerToken = new(float64)
				*_m.OutputCostPerToken = value.Float64
			}
		case modelpricing.FieldCacheReadInputTokenCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_input_token_cost", values[i])
			} else if value.Valid {
				_m.CacheReadInputTokenCost = new(float64)
				*_m.CacheReadInputTokenCost = value.Float64
			}
		case modelpricing.FieldCacheCreationInputTokenCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_input_token_cost", values[i])
			} else if value.Valid {
				_m.CacheCreationInputTokenCost = new(float64)
				*_m.CacheCreationInputTokenCost = value.Float64
			}
		case modelpricing.FieldIsCustom:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_custom", values[i])
			} else if value.Valid {
				_m.IsCustom = value.Bool
			}
		case modelpricing.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case modelpricing.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelpricing.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelPricing.
// This includes values selected through modifiers, order, etc.
func (_m *ModelPricing) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ModelPricing.
// Note that you need to call ModelPricing.Unwrap() before calling this method if this ModelPricing
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelPricing) Update() *ModelPricingUpdateOne {
	return NewModelPricingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelPricing entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelPricing) Unwrap() *ModelPricing {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelPricing is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelPricing) String() string {
	var builder strings.Builder
	builder.WriteString("ModelPricing(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("model_name=")
	builder.WriteString(_m.ModelName)
	builder.WriteString(", ")
	if v := _m.InputCostPerToken; v != nil {
		builder.WriteString("input_cost_per_token=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputCostPerToken; v != nil {
		builder.WriteString("output_cost_per_token=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheReadInputTokenCost; v != nil {
		builder.WriteString("cache_read_input_token_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheCreationInputTokenCost; v != nil {
		builder.WriteString("cache_creation_input_token_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_custom=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCustom))
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ModelPricings is a parsable slice of ModelPricing.
type ModelPricings []*ModelPricing
