// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelpricing"
)

// ModelPricingCreate is the builder for creating a ModelPricing entity.
type ModelPricingCreate struct {
	config
	mutation *ModelPricingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetModelName sets the "model_name" field.
func (_c *ModelPricingCreate) SetModelName(v string) *ModelPricingCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetInputCostPerToken sets the "input_cost_per_token" field.
func (_c *ModelPricingCreate) SetInputCostPerToken(v float64) *ModelPricingCreate {
	_c.mutation.SetInputCostPerToken(v)
	return _c
}

// SetNillableInputCostPerToken sets the "input_cost_per_token" field if the given value is not nil.
func (_c *ModelPricingCreate) SetNillableInputCostPerToken(v *float64) *ModelPricingCreate {
	if v != nil {
		_c.SetInputCostPerToken(*v)
	}
	return _c
}

// SetOutputCostPerToken sets the "output_cost_per_token" field.
func (_c *ModelPricingCreate) SetOutputCostPerToken(v float64) *ModelPricingCreate {
	_c.mutation.SetOutputCostPerToken(v)
	return _c
}

// SetNillableOutputCostPerToken sets the "output_cost_per_token" field if the given value is not nil.
func (_c *ModelPricingCreate) SetNillableOutputCostPerToken(v *float64) *ModelPricingCreate {
	if v != nil {
		_c.SetOutputCostPerToken(*v)
	}
	return _c
}

// SetCacheReadInputTokenCost sets the "cache_read_input_token_cost" field.
func (_c *ModelPricingCreate) SetCacheReadInputTokenCost(v float64) *ModelPricingCreate {
	_c.mutation.SetCacheReadInputTokenCost(v)
	return _c
}

// SetNillableCacheReadInputTokenCost sets the "cache_read_input_token_cost" field if the given value is not nil.
func (_c *ModelPricingCreate) SetNillableCacheReadInputTokenCost(v *float64) *ModelPricingCreate {
	if v != nil {
		_c.SetCacheReadInputTokenCost(*v)
	}
	return _c
}

// SetCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field.
func (_c *ModelPricingCreate) SetCacheCreationInputTokenCost(v float64) *ModelPricingCreate {
	_c.mutation.SetCacheCreationInputTokenCost(v)
	return _c
}

// SetNillableCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field if the given value is not nil.
func (_c *ModelPricingCreate) SetNillableCacheCreationInputTokenCost(v *float64) *ModelPricingCreate {
	if v != nil {
		_c.SetCacheCreationInputTokenCost(*v)
	}
	return _c
}

// SetIsCustom sets the "is_custom" field.
func (_c *ModelPricingCreate) SetIsCustom(v bool) *ModelPricingCreate {
	_c.mutation.SetIsCustom(v)
	return _c
}

// SetNillableIsCustom sets the "is_custom" field if the given value is not nil.
func (_c *ModelPricingCreate) SetNillableIsCustom(v *bool) *ModelPricingCreate {
	if v != nil {
		_c.SetIsCustom(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *ModelPricingCreate) SetNote(v string) *ModelPricingCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *ModelPricingCreate) SetNillableNote(v *string) *ModelPricingCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelPricingCreate) SetCreatedAt(v time.Time) *ModelPricingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelPricingCreate) SetNillableCreatedAt(v *time.Time) *ModelPricingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelPricingCreate) SetUpdatedAt(v time.Time) *ModelPricingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelPricingCreate) SetNillableUpdatedAt(v *time.Time) *ModelPricingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetFastPriceMultiplier sets the "fast_price_multiplier" field.
func (_c *ModelPricingCreate) SetFastPriceMultiplier(v float64) *ModelPricingCreate {
	_c.mutation.SetFastPriceMultiplier(v)
	return _c
}

// SetNillableFastPriceMultiplier sets the "fast_price_multiplier" field if the given value is not nil.
func (_c *ModelPricingCreate) SetNillableFastPriceMultiplier(v *float64) *ModelPricingCreate {
	if v != nil {
		_c.SetFastPriceMultiplier(*v)
	}
	return _c
}

// Mutation returns the ModelPricingMutation object of the builder.
func (_c *ModelPricingCreate) Mutation() *ModelPricingMutation {
	return _c.mutation
}

// Save creates the ModelPricing in the database.
func (_c *ModelPricingCreate) Save(ctx context.Context) (*ModelPricing, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelPricingCreate) SaveX(ctx context.Context) *ModelPricing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelPricingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelPricingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelPricingCreate) defaults() {
	if _, ok := _c.mutation.IsCustom(); !ok {
		v := modelpricing.DefaultIsCustom
		_c.mutation.SetIsCustom(v)
	}
	if _, ok := _c.mutation.Note(); !ok {
		v := modelpricing.DefaultNote
		_c.mutation.SetNote(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelpricing.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelpricing.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelPricingCreate) check() error {
	if _, ok := _c.mutation.ModelName(); !ok {
		return &ValidationError{Name: "model_name", err: errors.New(`ent: missing required field "ModelPricing.model_name"`)}
	}
	if v, ok := _c.mutation.ModelName(); ok {
		if err := modelpricing.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.model_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsCustom(); !ok {
		return &ValidationError{Name: "is_custom", err: errors.New(`ent: missing required field "ModelPricing.is_custom"`)}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "ModelPricing.note"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelPricing.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelPricing.updated_at"`)}
	}
	return nil
}

func (_c *ModelPricingCreate) sqlSave(ctx context.Context) (*ModelPricing, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelPricingCreate) createSpec() (*ModelPricing, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelPricing{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelpricing.Table, sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(modelpricing.FieldModelName, field.TypeString, value)
		_node.ModelName = value
	}
	if value, ok := _c.mutation.InputCostPerToken(); ok {
		_spec.SetField(modelpricing.FieldInputCostPerToken, field.TypeFloat64, value)
		_node.InputCostPerToken = &value
	}
	if value, ok := _c.mutation.OutputCostPerToken(); ok {
		_spec.SetField(modelpricing.FieldOutputCostPerToken, field.TypeFloat64, value)
		_node.OutputCostPerToken = &value
	}
	if value, ok := _c.mutation.CacheReadInputTokenCost(); ok {
		_spec.SetField(modelpricing.FieldCacheReadInputTokenCost, field.TypeFloat64, value)
		_node.CacheReadInputTokenCost = &value
	}
	if value, ok := _c.mutation.CacheCreationInputTokenCost(); ok {
		_spec.SetField(modelpricing.FieldCacheCreationInputTokenCost, field.TypeFloat64, value)
		_node.CacheCreationInputTokenCost = &value
	}
	if value, ok := _c.mutation.IsCustom(); ok {
		_spec.SetField(modelpricing.FieldIsCustom, field.TypeBool, value)
		_node.IsCustom = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(modelpricing.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelpricing.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpricing.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.FastPriceMultiplier(); ok {
		_spec.SetField(modelpricing.FieldFastPriceMultiplier, field.TypeFloat64, value)
		_node.FastPriceMultiplier = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelPricing.Create().
//		SetModelName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelPricingUpsert) {
//			SetModelName(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelPricingCreate) OnConflict(opts ...sql.ConflictOption) *ModelPricingUpsertOne {
	_c.conflict = opts
	return &ModelPricingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelPricing.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelPricingCreate) OnConflictColumns(columns ...string) *ModelPricingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelPricingUpsertOne{
		create: _c,
	}
}

type (
	// ModelPricingUpsertOne is the builder for "upsert"-ing
	//  one ModelPricing node.
	ModelPricingUpsertOne struct {
		create *ModelPricingCreate
	}

	// ModelPricingUpsert is the "OnConflict" setter.
	ModelPricingUpsert struct {
		*sql.UpdateSet
	}
)

// SetModelName sets the "model_name" field.
func (u *ModelPricingUpsert) SetModelName(v string) *ModelPricingUpsert {
	u.Set(modelpricing.FieldModelName, v)
	return u
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *ModelPricingUpsert) UpdateModelName() *ModelPricingUpsert {
	u.SetExcluded(modelpricing.FieldModelName)
	return u
}

// SetInputCostPerToken sets the "input_cost_per_token" field.
func (u *ModelPricingUpsert) SetInputCostPerToken(v float64) *ModelPricingUpsert {
	u.Set(modelpricing.FieldInputCostPerToken, v)
	return u
}

// UpdateInputCostPerToken sets the "input_cost_per_token" field to the value that was provided on create.
func (u *ModelPricingUpsert) UpdateInputCostPerToken() *ModelPricingUpsert {
	u.SetExcluded(modelpricing.FieldInputCostPerToken)
	return u
}

// AddInputCostPerToken adds v to the "input_cost_per_token" field.
func (u *ModelPricingUpsert) AddInputCostPerToken(v float64) *ModelPricingUpsert {
	u.Add(modelpricing.FieldInputCostPerToken, v)
	return u
}

// ClearInputCostPerToken clears the value of the "input_cost_per_token" field.
func (u *ModelPricingUpsert) ClearInputCostPerToken() *ModelPricingUpsert {
	u.SetNull(modelpricing.FieldInputCostPerToken)
	return u
}

// SetOutputCostPerToken sets the "output_cost_per_token" field.
func (u *ModelPricingUpsert) SetOutputCostPerToken(v float64) *ModelPricingUpsert {
	u.Set(modelpricing.FieldOutputCostPerToken, v)
	return u
}

// UpdateOutputCostPerToken sets the "output_cost_per_token" field to the value that was provided on create.
func (u *ModelPricingUpsert) UpdateOutputCostPerToken() *ModelPricingUpsert {
	u.SetExcluded(modelpricing.FieldOutputCostPerToken)
	return u
}

// AddOutputCostPerToken adds v to the "output_cost_per_token" field.
func (u *ModelPricingUpsert) AddOutputCostPerToken(v float64) *ModelPricingUpsert {
	u.Add(modelpricing.FieldOutputCostPerToken, v)
	return u
}

// ClearOutputCostPerToken clears the value of the "output_cost_per_token" field.
func (u *ModelPricingUpsert) ClearOutputCostPerToken() *ModelPricingUpsert {
	u.SetNull(modelpricing.FieldOutputCostPerToken)
	return u
}

// SetCacheReadInputTokenCost sets the "cache_read_input_token_cost" field.
func (u *ModelPricingUpsert) SetCacheReadInputTokenCost(v float64) *ModelPricingUpsert {
	u.Set(modelpricing.FieldCacheReadInputTokenCost, v)
	return u
}

// UpdateCacheReadInputTokenCost sets the "cache_read_input_token_cost" field to the value that was provided on create.
func (u *ModelPricingUpsert) UpdateCacheReadInputTokenCost() *ModelPricingUpsert {
	u.SetExcluded(modelpricing.FieldCacheReadInputTokenCost)
	return u
}

// AddCacheReadInputTokenCost adds v to the "cache_read_input_token_cost" field.
func (u *ModelPricingUpsert) AddCacheReadInputTokenCost(v float64) *ModelPricingUpsert {
	u.Add(modelpricing.FieldCacheReadInputTokenCost, v)
	return u
}

// ClearCacheReadInputTokenCost clears the value of the "cache_read_input_token_cost" field.
func (u *ModelPricingUpsert) ClearCacheReadInputTokenCost() *ModelPricingUpsert {
	u.SetNull(modelpricing.FieldCacheReadInputTokenCost)
	return u
}

// SetCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field.
func (u *ModelPricingUpsert) SetCacheCreationInputTokenCost(v float64) *ModelPricingUpsert {
	u.Set(modelpricing.FieldCacheCreationInputTokenCost, v)
	return u
}

// UpdateCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field to the value that was provided on create.
func (u *ModelPricingUpsert) UpdateCacheCreationInputTokenCost() *ModelPricingUpsert {
	u.SetExcluded(modelpricing.FieldCacheCreationInputTokenCost)
	return u
}

// AddCacheCreationInputTokenCost adds v to the "cache_creation_input_token_cost" field.
func (u *ModelPricingUpsert) AddCacheCreationInputTokenCost(v float64) *ModelPricingUpsert {
	u.Add(modelpricing.FieldCacheCreationInputTokenCost, v)
	return u
}

// ClearCacheCreationInputTokenCost clears the value of the "cache_creation_input_token_cost" field.
func (u *ModelPricingUpsert) ClearCacheCreationInputTokenCost() *ModelPricingUpsert {
	u.SetNull(modelpricing.FieldCacheCreationInputTokenCost)
	return u
}

// SetIsCustom sets the "is_custom" field.
func (u *ModelPricingUpsert) SetIsCustom(v bool) *ModelPricingUpsert {
	u.Set(modelpricing.FieldIsCustom, v)
	return u
}

// UpdateIsCustom sets the "is_custom" field to the value that was provided on create.
func (u *ModelPricingUpsert) UpdateIsCustom() *ModelPricingUpsert {
	u.SetExcluded(modelpricing.FieldIsCustom)
	return u
}

// SetNote sets the "note" field.
func (u *ModelPricingUpsert) SetNote(v string) *ModelPricingUpsert {
	u.Set(modelpricing.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ModelPricingUpsert) UpdateNote() *ModelPricingUpsert {
	u.SetExcluded(modelpricing.FieldNote)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelPricingUpsert) SetUpdatedAt(v time.Time) *ModelPricingUpsert {
	u.Set(modelpricing.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelPricingUpsert) UpdateUpdatedAt() *ModelPricingUpsert {
	u.SetExcluded(modelpricing.FieldUpdatedAt)
	return u
}

// SetFastPriceMultiplier sets the "fast_price_multiplier" field.
func (u *ModelPricingUpsert) SetFastPriceMultiplier(v float64) *ModelPricingUpsert {
	u.Set(modelpricing.FieldFastPriceMultiplier, v)
	return u
}

// UpdateFastPriceMultiplier sets the "fast_price_multiplier" field to the value that was provided on create.
func (u *ModelPricingUpsert) UpdateFastPriceMultiplier() *ModelPricingUpsert {
	u.SetExcluded(modelpricing.FieldFastPriceMultiplier)
	return u
}

// AddFastPriceMultiplier adds v to the "fast_price_multiplier" field.
func (u *ModelPricingUpsert) AddFastPriceMultiplier(v float64) *ModelPricingUpsert {
	u.Add(modelpricing.FieldFastPriceMultiplier, v)
	return u
}

// ClearFastPriceMultiplier clears the value of the "fast_price_multiplier" field.
func (u *ModelPricingUpsert) ClearFastPriceMultiplier() *ModelPricingUpsert {
	u.SetNull(modelpricing.FieldFastPriceMultiplier)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelPricing.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelPricingUpsertOne) UpdateNewValues() *ModelPricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelpricing.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelPricing.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelPricingUpsertOne) Ignore() *ModelPricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelPricingUpsertOne) DoNothing() *ModelPricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelPricingCreate.OnConflict
// documentation for more info.
func (u *ModelPricingUpsertOne) Update(set func(*ModelPricingUpsert)) *ModelPricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelPricingUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelName sets the "model_name" field.
func (u *ModelPricingUpsertOne) SetModelName(v string) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *ModelPricingUpsertOne) UpdateModelName() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateModelName()
	})
}

// SetInputCostPerToken sets the "input_cost_per_token" field.
func (u *ModelPricingUpsertOne) SetInputCostPerToken(v float64) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetInputCostPerToken(v)
	})
}

// AddInputCostPerToken adds v to the "input_cost_per_token" field.
func (u *ModelPricingUpsertOne) AddInputCostPerToken(v float64) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.AddInputCostPerToken(v)
	})
}

// UpdateInputCostPerToken sets the "input_cost_per_token" field to the value that was provided on create.
func (u *ModelPricingUpsertOne) UpdateInputCostPerToken() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateInputCostPerToken()
	})
}

// ClearInputCostPerToken clears the value of the "input_cost_per_token" field.
func (u *ModelPricingUpsertOne) ClearInputCostPerToken() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.ClearInputCostPerToken()
	})
}

// SetOutputCostPerToken sets the "output_cost_per_token" field.
func (u *ModelPricingUpsertOne) SetOutputCostPerToken(v float64) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetOutputCostPerToken(v)
	})
}

// AddOutputCostPerToken adds v to the "output_cost_per_token" field.
func (u *ModelPricingUpsertOne) AddOutputCostPerToken(v float64) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.AddOutputCostPerToken(v)
	})
}

// UpdateOutputCostPerToken sets the "output_cost_per_token" field to the value that was provided on create.
func (u *ModelPricingUpsertOne) UpdateOutputCostPerToken() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateOutputCostPerToken()
	})
}

// ClearOutputCostPerToken clears the value of the "output_cost_per_token" field.
func (u *ModelPricingUpsertOne) ClearOutputCostPerToken() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.ClearOutputCostPerToken()
	})
}

// SetCacheReadInputTokenCost sets the "cache_read_input_token_cost" field.
func (u *ModelPricingUpsertOne) SetCacheReadInputTokenCost(v float64) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetCacheReadInputTokenCost(v)
	})
}

// AddCacheReadInputTokenCost adds v to the "cache_read_input_token_cost" field.
func (u *ModelPricingUpsertOne) AddCacheReadInputTokenCost(v float64) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.AddCacheReadInputTokenCost(v)
	})
}

// UpdateCacheReadInputTokenCost sets the "cache_read_input_token_cost" field to the value that was provided on create.
func (u *ModelPricingUpsertOne) UpdateCacheReadInputTokenCost() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateCacheReadInputTokenCost()
	})
}

// ClearCacheReadInputTokenCost clears the value of the "cache_read_input_token_cost" field.
func (u *ModelPricingUpsertOne) ClearCacheReadInputTokenCost() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.ClearCacheReadInputTokenCost()
	})
}

// SetCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field.
func (u *ModelPricingUpsertOne) SetCacheCreationInputTokenCost(v float64) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetCacheCreationInputTokenCost(v)
	})
}

// AddCacheCreationInputTokenCost adds v to the "cache_creation_input_token_cost" field.
func (u *ModelPricingUpsertOne) AddCacheCreationInputTokenCost(v float64) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.AddCacheCreationInputTokenCost(v)
	})
}

// UpdateCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field to the value that was provided on create.
func (u *ModelPricingUpsertOne) UpdateCacheCreationInputTokenCost() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateCacheCreationInputTokenCost()
	})
}

// ClearCacheCreationInputTokenCost clears the value of the "cache_creation_input_token_cost" field.
func (u *ModelPricingUpsertOne) ClearCacheCreationInputTokenCost() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.ClearCacheCreationInputTokenCost()
	})
}

// SetIsCustom sets the "is_custom" field.
func (u *ModelPricingUpsertOne) SetIsCustom(v bool) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetIsCustom(v)
	})
}

// UpdateIsCustom sets the "is_custom" field to the value that was provided on create.
func (u *ModelPricingUpsertOne) UpdateIsCustom() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateIsCustom()
	})
}

// SetNote sets the "note" field.
func (u *ModelPricingUpsertOne) SetNote(v string) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ModelPricingUpsertOne) UpdateNote() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateNote()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelPricingUpsertOne) SetUpdatedAt(v time.Time) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelPricingUpsertOne) UpdateUpdatedAt() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetFastPriceMultiplier sets the "fast_price_multiplier" field.
func (u *ModelPricingUpsertOne) SetFastPriceMultiplier(v float64) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetFastPriceMultiplier(v)
	})
}

// AddFastPriceMultiplier adds v to the "fast_price_multiplier" field.
func (u *ModelPricingUpsertOne) AddFastPriceMultiplier(v float64) *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.AddFastPriceMultiplier(v)
	})
}

// UpdateFastPriceMultiplier sets the "fast_price_multiplier" field to the value that was provided on create.
func (u *ModelPricingUpsertOne) UpdateFastPriceMultiplier() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateFastPriceMultiplier()
	})
}

// ClearFastPriceMultiplier clears the value of the "fast_price_multiplier" field.
func (u *ModelPricingUpsertOne) ClearFastPriceMultiplier() *ModelPricingUpsertOne {
	return u.Update(func(s *ModelPricingUpsert) {
		s.ClearFastPriceMultiplier()
	})
}

// Exec executes the query.
func (u *ModelPricingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelPricingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelPricingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelPricingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelPricingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelPricingCreateBulk is the builder for creating many ModelPricing entities in bulk.
type ModelPricingCreateBulk struct {
	config
	err      error
	builders []*ModelPricingCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelPricing entities in the database.
func (_c *ModelPricingCreateBulk) Save(ctx context.Context) ([]*ModelPricing, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelPricing, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelPricingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelPricingCreateBulk) SaveX(ctx context.Context) []*ModelPricing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelPricingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelPricingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelPricing.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelPricingUpsert) {
//			SetModelName(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelPricingCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelPricingUpsertBulk {
	_c.conflict = opts
	return &ModelPricingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelPricing.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelPricingCreateBulk) OnConflictColumns(columns ...string) *ModelPricingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelPricingUpsertBulk{
		create: _c,
	}
}

// ModelPricingUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelPricing nodes.
type ModelPricingUpsertBulk struct {
	create *ModelPricingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelPricing.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelPricingUpsertBulk) UpdateNewValues() *ModelPricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelpricing.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelPricing.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelPricingUpsertBulk) Ignore() *ModelPricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelPricingUpsertBulk) DoNothing() *ModelPricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelPricingCreateBulk.OnConflict
// documentation for more info.
func (u *ModelPricingUpsertBulk) Update(set func(*ModelPricingUpsert)) *ModelPricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelPricingUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelName sets the "model_name" field.
func (u *ModelPricingUpsertBulk) SetModelName(v string) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *ModelPricingUpsertBulk) UpdateModelName() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateModelName()
	})
}

// SetInputCostPerToken sets the "input_cost_per_token" field.
func (u *ModelPricingUpsertBulk) SetInputCostPerToken(v float64) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetInputCostPerToken(v)
	})
}

// AddInputCostPerToken adds v to the "input_cost_per_token" field.
func (u *ModelPricingUpsertBulk) AddInputCostPerToken(v float64) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.AddInputCostPerToken(v)
	})
}

// UpdateInputCostPerToken sets the "input_cost_per_token" field to the value that was provided on create.
func (u *ModelPricingUpsertBulk) UpdateInputCostPerToken() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateInputCostPerToken()
	})
}

// ClearInputCostPerToken clears the value of the "input_cost_per_token" field.
func (u *ModelPricingUpsertBulk) ClearInputCostPerToken() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.ClearInputCostPerToken()
	})
}

// SetOutputCostPerToken sets the "output_cost_per_token" field.
func (u *ModelPricingUpsertBulk) SetOutputCostPerToken(v float64) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetOutputCostPerToken(v)
	})
}

// AddOutputCostPerToken adds v to the "output_cost_per_token" field.
func (u *ModelPricingUpsertBulk) AddOutputCostPerToken(v float64) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.AddOutputCostPerToken(v)
	})
}

// UpdateOutputCostPerToken sets the "output_cost_per_token" field to the value that was provided on create.
func (u *ModelPricingUpsertBulk) UpdateOutputCostPerToken() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateOutputCostPerToken()
	})
}

// ClearOutputCostPerToken clears the value of the "output_cost_per_token" field.
func (u *ModelPricingUpsertBulk) ClearOutputCostPerToken() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.ClearOutputCostPerToken()
	})
}

// SetCacheReadInputTokenCost sets the "cache_read_input_token_cost" field.
func (u *ModelPricingUpsertBulk) SetCacheReadInputTokenCost(v float64) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetCacheReadInputTokenCost(v)
	})
}

// AddCacheReadInputTokenCost adds v to the "cache_read_input_token_cost" field.
func (u *ModelPricingUpsertBulk) AddCacheReadInputTokenCost(v float64) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.AddCacheReadInputTokenCost(v)
	})
}

// UpdateCacheReadInputTokenCost sets the "cache_read_input_token_cost" field to the value that was provided on create.
func (u *ModelPricingUpsertBulk) UpdateCacheReadInputTokenCost() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateCacheReadInputTokenCost()
	})
}

// ClearCacheReadInputTokenCost clears the value of the "cache_read_input_token_cost" field.
func (u *ModelPricingUpsertBulk) ClearCacheReadInputTokenCost() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.ClearCacheReadInputTokenCost()
	})
}

// SetCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field.
func (u *ModelPricingUpsertBulk) SetCacheCreationInputTokenCost(v float64) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetCacheCreationInputTokenCost(v)
	})
}

// AddCacheCreationInputTokenCost adds v to the "cache_creation_input_token_cost" field.
func (u *ModelPricingUpsertBulk) AddCacheCreationInputTokenCost(v float64) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.AddCacheCreationInputTokenCost(v)
	})
}

// UpdateCacheCreationInputTokenCost sets the "cache_creation_input_token_cost" field to the value that was provided on create.
func (u *ModelPricingUpsertBulk) UpdateCacheCreationInputTokenCost() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateCacheCreationInputTokenCost()
	})
}

// ClearCacheCreationInputTokenCost clears the value of the "cache_creation_input_token_cost" field.
func (u *ModelPricingUpsertBulk) ClearCacheCreationInputTokenCost() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.ClearCacheCreationInputTokenCost()
	})
}

// SetIsCustom sets the "is_custom" field.
func (u *ModelPricingUpsertBulk) SetIsCustom(v bool) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetIsCustom(v)
	})
}

// UpdateIsCustom sets the "is_custom" field to the value that was provided on create.
func (u *ModelPricingUpsertBulk) UpdateIsCustom() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateIsCustom()
	})
}

// SetNote sets the "note" field.
func (u *ModelPricingUpsertBulk) SetNote(v string) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ModelPricingUpsertBulk) UpdateNote() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateNote()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelPricingUpsertBulk) SetUpdatedAt(v time.Time) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelPricingUpsertBulk) UpdateUpdatedAt() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetFastPriceMultiplier sets the "fast_price_multiplier" field.
func (u *ModelPricingUpsertBulk) SetFastPriceMultiplier(v float64) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.SetFastPriceMultiplier(v)
	})
}

// AddFastPriceMultiplier adds v to the "fast_price_multiplier" field.
func (u *ModelPricingUpsertBulk) AddFastPriceMultiplier(v float64) *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.AddFastPriceMultiplier(v)
	})
}

// UpdateFastPriceMultiplier sets the "fast_price_multiplier" field to the value that was provided on create.
func (u *ModelPricingUpsertBulk) UpdateFastPriceMultiplier() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.UpdateFastPriceMultiplier()
	})
}

// ClearFastPriceMultiplier clears the value of the "fast_price_multiplier" field.
func (u *ModelPricingUpsertBulk) ClearFastPriceMultiplier() *ModelPricingUpsertBulk {
	return u.Update(func(s *ModelPricingUpsert) {
		s.ClearFastPriceMultiplier()
	})
}

// Exec executes the query.
func (u *ModelPricingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelPricingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelPricingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelPricingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
