// Code generated by ent, DO NOT EDIT.

package modelpricing

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the modelpricing type in the database.
	Label = "model_pricing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelName holds the string denoting the model_name field in the database.
	FieldModelName = "model_name"
	// FieldInputCostPerToken holds the string denoting the input_cost_per_token field in the database.
	FieldInputCostPerToken = "input_cost_per_token"
	// FieldOutputCostPerToken holds the string denoting the output_cost_per_token field in the database.
	FieldOutputCostPerToken = "output_cost_per_token"
	// FieldCacheReadInputTokenCost holds the string denoting the cache_read_input_token_cost field in the database.
	FieldCacheReadInputTokenCost = "cache_read_input_token_cost"
	// FieldCacheCreationInputTokenCost holds the string denoting the cache_creation_input_token_cost field in the database.
	FieldCacheCreationInputTokenCost = "cache_creation_input_token_cost"
	// FieldIsCustom holds the string denoting the is_custom field in the database.
	FieldIsCustom = "is_custom"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldFastPriceMultiplier holds the string denoting the fast_price_multiplier field in the database.
	FieldFastPriceMultiplier = "fast_price_multiplier"
	// Table holds the table name of the modelpricing in the database.
	Table = "model_pricings"
)

// Columns holds all SQL columns for modelpricing fields.
var Columns = []string{
	FieldID,
	FieldModelName,
	FieldInputCostPerToken,
	FieldOutputCostPerToken,
	FieldCacheReadInputTokenCost,
	FieldCacheCreationInputTokenCost,
	FieldIsCustom,
	FieldNote,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldFastPriceMultiplier,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelNameValidator is a validator for the "model_name" field. It is called by the builders before save.
	ModelNameValidator func(string) error
	// DefaultIsCustom holds the default value on creation for the "is_custom" field.
	DefaultIsCustom bool
	// DefaultNote holds the default value on creation for the "note" field.
	DefaultNote string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ModelPricing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelName orders the results by the model_name field.
func ByModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelName, opts...).ToFunc()
}

// ByInputCostPerToken orders the results by the input_cost_per_token field.
func ByInputCostPerToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputCostPerToken, opts...).ToFunc()
}

// ByOutputCostPerToken orders the results by the output_cost_per_token field.
func ByOutputCostPerToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputCostPerToken, opts...).ToFunc()
}

// ByCacheReadInputTokenCost orders the results by the cache_read_input_token_cost field.
func ByCacheReadInputTokenCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadInputTokenCost, opts...).ToFunc()
}

// ByCacheCreationInputTokenCost orders the results by the cache_creation_input_token_cost field.
func ByCacheCreationInputTokenCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreationInputTokenCost, opts...).ToFunc()
}

// ByIsCustom orders the results by the is_custom field.
func ByIsCustom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCustom, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByFastPriceMultiplier orders the results by the fast_price_multiplier field.
func ByFastPriceMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFastPriceMultiplier, opts...).ToFunc()
}
