// Code generated by ent, DO NOT EDIT.

package modelpricing

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldID, id))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldModelName, v))
}

// InputCostPerToken applies equality check predicate on the "input_cost_per_token" field. It's identical to InputCostPerTokenEQ.
func InputCostPerToken(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldInputCostPerToken, v))
}

// OutputCostPerToken applies equality check predicate on the "output_cost_per_token" field. It's identical to OutputCostPerTokenEQ.
func OutputCostPerToken(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldOutputCostPerToken, v))
}

// CacheReadInputTokenCost applies equality check predicate on the "cache_read_input_token_cost" field. It's identical to CacheReadInputTokenCostEQ.
func CacheReadInputTokenCost(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldCacheReadInputTokenCost, v))
}

// CacheCreationInputTokenCost applies equality check predicate on the "cache_creation_input_token_cost" field. It's identical to CacheCreationInputTokenCostEQ.
func CacheCreationInputTokenCost(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldCacheCreationInputTokenCost, v))
}

// IsCustom applies equality check predicate on the "is_custom" field. It's identical to IsCustomEQ.
func IsCustom(v bool) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldIsCustom, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldContainsFold(FieldModelName, v))
}

// InputCostPerTokenEQ applies the EQ predicate on the "input_cost_per_token" field.
func InputCostPerTokenEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldInputCostPerToken, v))
}

// InputCostPerTokenNEQ applies the NEQ predicate on the "input_cost_per_token" field.
func InputCostPerTokenNEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldInputCostPerToken, v))
}

// InputCostPerTokenIn applies the In predicate on the "input_cost_per_token" field.
func InputCostPerTokenIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldInputCostPerToken, vs...))
}

// InputCostPerTokenNotIn applies the NotIn predicate on the "input_cost_per_token" field.
func InputCostPerTokenNotIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldInputCostPerToken, vs...))
}

// InputCostPerTokenGT applies the GT predicate on the "input_cost_per_token" field.
func InputCostPerTokenGT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldInputCostPerToken, v))
}

// InputCostPerTokenGTE applies the GTE predicate on the "input_cost_per_token" field.
func InputCostPerTokenGTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldInputCostPerToken, v))
}

// InputCostPerTokenLT applies the LT predicate on the "input_cost_per_token" field.
func InputCostPerTokenLT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldInputCostPerToken, v))
}

// InputCostPerTokenLTE applies the LTE predicate on the "input_cost_per_token" field.
func InputCostPerTokenLTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldInputCostPerToken, v))
}

// InputCostPerTokenIsNil applies the IsNil predicate on the "input_cost_per_token" field.
func InputCostPerTokenIsNil() predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIsNull(FieldInputCostPerToken))
}

// InputCostPerTokenNotNil applies the NotNil predicate on the "input_cost_per_token" field.
func InputCostPerTokenNotNil() predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotNull(FieldInputCostPerToken))
}

// OutputCostPerTokenEQ applies the EQ predicate on the "output_cost_per_token" field.
func OutputCostPerTokenEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldOutputCostPerToken, v))
}

// OutputCostPerTokenNEQ applies the NEQ predicate on the "output_cost_per_token" field.
func OutputCostPerTokenNEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldOutputCostPerToken, v))
}

// OutputCostPerTokenIn applies the In predicate on the "output_cost_per_token" field.
func OutputCostPerTokenIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldOutputCostPerToken, vs...))
}

// OutputCostPerTokenNotIn applies the NotIn predicate on the "output_cost_per_token" field.
func OutputCostPerTokenNotIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldOutputCostPerToken, vs...))
}

// OutputCostPerTokenGT applies the GT predicate on the "output_cost_per_token" field.
func OutputCostPerTokenGT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldOutputCostPerToken, v))
}

// OutputCostPerTokenGTE applies the GTE predicate on the "output_cost_per_token" field.
func OutputCostPerTokenGTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldOutputCostPerToken, v))
}

// OutputCostPerTokenLT applies the LT predicate on the "output_cost_per_token" field.
func OutputCostPerTokenLT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldOutputCostPerToken, v))
}

// OutputCostPerTokenLTE applies the LTE predicate on the "output_cost_per_token" field.
func OutputCostPerTokenLTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldOutputCostPerToken, v))
}

// OutputCostPerTokenIsNil applies the IsNil predicate on the "output_cost_per_token" field.
func OutputCostPerTokenIsNil() predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIsNull(FieldOutputCostPerToken))
}

// OutputCostPerTokenNotNil applies the NotNil predicate on the "output_cost_per_token" field.
func OutputCostPerTokenNotNil() predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotNull(FieldOutputCostPerToken))
}

// CacheReadInputTokenCostEQ applies the EQ predicate on the "cache_read_input_token_cost" field.
func CacheReadInputTokenCostEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldCacheReadInputTokenCost, v))
}

// CacheReadInputTokenCostNEQ applies the NEQ predicate on the "cache_read_input_token_cost" field.
func CacheReadInputTokenCostNEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldCacheReadInputTokenCost, v))
}

// CacheReadInputTokenCostIn applies the In predicate on the "cache_read_input_token_cost" field.
func CacheReadInputTokenCostIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldCacheReadInputTokenCost, vs...))
}

// CacheReadInputTokenCostNotIn applies the NotIn predicate on the "cache_read_input_token_cost" field.
func CacheReadInputTokenCostNotIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldCacheReadInputTokenCost, vs...))
}

// CacheReadInputTokenCostGT applies the GT predicate on the "cache_read_input_token_cost" field.
func CacheReadInputTokenCostGT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldCacheReadInputTokenCost, v))
}

// CacheReadInputTokenCostGTE applies the GTE predicate on the "cache_read_input_token_cost" field.
func CacheReadInputTokenCostGTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldCacheReadInputTokenCost, v))
}

// CacheReadInputTokenCostLT applies the LT predicate on the "cache_read_input_token_cost" field.
func CacheReadInputTokenCostLT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldCacheReadInputTokenCost, v))
}

// CacheReadInputTokenCostLTE applies the LTE predicate on the "cache_read_input_token_cost" field.
func CacheReadInputTokenCostLTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldCacheReadInputTokenCost, v))
}

// CacheReadInputTokenCostIsNil applies the IsNil predicate on the "cache_read_input_token_cost" field.
func CacheReadInputTokenCostIsNil() predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIsNull(FieldCacheReadInputTokenCost))
}

// CacheReadInputTokenCostNotNil applies the NotNil predicate on the "cache_read_input_token_cost" field.
func CacheReadInputTokenCostNotNil() predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotNull(FieldCacheReadInputTokenCost))
}

// CacheCreationInputTokenCostEQ applies the EQ predicate on the "cache_creation_input_token_cost" field.
func CacheCreationInputTokenCostEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldCacheCreationInputTokenCost, v))
}

// CacheCreationInputTokenCostNEQ applies the NEQ predicate on the "cache_creation_input_token_cost" field.
func CacheCreationInputTokenCostNEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldCacheCreationInputTokenCost, v))
}

// CacheCreationInputTokenCostIn applies the In predicate on the "cache_creation_input_token_cost" field.
func CacheCreationInputTokenCostIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldCacheCreationInputTokenCost, vs...))
}

// CacheCreationInputTokenCostNotIn applies the NotIn predicate on the "cache_creation_input_token_cost" field.
func CacheCreationInputTokenCostNotIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldCacheCreationInputTokenCost, vs...))
}

// CacheCreationInputTokenCostGT applies the GT predicate on the "cache_creation_input_token_cost" field.
func CacheCreationInputTokenCostGT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldCacheCreationInputTokenCost, v))
}

// CacheCreationInputTokenCostGTE applies the GTE predicate on the "cache_creation_input_token_cost" field.
func CacheCreationInputTokenCostGTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldCacheCreationInputTokenCost, v))
}

// CacheCreationInputTokenCostLT applies the LT predicate on the "cache_creation_input_token_cost" field.
func CacheCreationInputTokenCostLT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldCacheCreationInputTokenCost, v))
}

// CacheCreationInputTokenCostLTE applies the LTE predicate on the "cache_creation_input_token_cost" field.
func CacheCreationInputTokenCostLTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldCacheCreationInputTokenCost, v))
}

// CacheCreationInputTokenCostIsNil applies the IsNil predicate on the "cache_creation_input_token_cost" field.
func CacheCreationInputTokenCostIsNil() predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIsNull(FieldCacheCreationInputTokenCost))
}

// CacheCreationInputTokenCostNotNil applies the NotNil predicate on the "cache_creation_input_token_cost" field.
func CacheCreationInputTokenCostNotNil() predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotNull(FieldCacheCreationInputTokenCost))
}

// IsCustomEQ applies the EQ predicate on the "is_custom" field.
func IsCustomEQ(v bool) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldIsCustom, v))
}

// IsCustomNEQ applies the NEQ predicate on the "is_custom" field.
func IsCustomNEQ(v bool) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldIsCustom, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelPricing) predicate.ModelPricing {
	return predicate.ModelPricing(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelPricing) predicate.ModelPricing {
	return predicate.ModelPricing(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelPricing) predicate.ModelPricing {
	return predicate.ModelPricing(sql.NotPredicates(p))
}
